### ISSUE TITLE
Bukkit/Spigot Bridge Plugin

### ISSUE THREAD

**Issue by B1acksheep** [alphartdev/BAT-WebInterface#13]
Many comfort features require a plugin which runs directly on the Spigot Server.
That is the reason why many BungeeCord plugins use an additional "Bridge plugin".

E.g. Freezing the player:  https://github.com/alphartdev/BAT-WebInterface/issues/12

**Comment by alphartdev** [comment]
Hi,
this has been an ongoing demand since BAT was launched (March 2014), however I always declined it because BAT is aiming at being a global network plugin, and as far as possible only a bungeecord one. And since BAT was launched I never really needed to setup a spigot bridge.

But as some users appreciate **comfort features** as you do, there are many plugins out there (ExecuteEverywhere and some others, just research spigot forums) providing this feature.

And just a last thing, I know you're more active on the WebInterface that on the plugin itself, but please post your issues related to the plugin in the repo of the plugin and not in the webinterface one. As the webinterface is less popular, it's likely less people will see it and it's a better organization as well! So I'll ask you to move your #12 and #14 issues to BAT repository itself.
