### ISSUE TITLE
Hide ip also in punishment list

### ISSUE THREAD

**Issue by alphartdev** [alphartdev/BAT-WebInterface#3]
Currently the IP field is hided on a player profile if you don't have an account.
But the ip on punishment list are still visible, they should be hided too, in order to stay consistent in the logic...

**Comment by KiloJuliet** [comment]
Quick hack (I'm no php programmer) in \views\ban\listbans.php
<td ><?php echo $ban['headImg']; if($this->isAdmin()) echo $ban['player']; if(!$this->isAdmin())echo 'IP Redacted';?></td>

Maybe add a regex for an ip pattern too?
something like
if(preg_match('/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/', $ban['player'])) echo 'IP Redacted';
if(!preg_match('/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/', $ban['player'])) echo $ban['player'];
Might look something like:

<td ><?php echo $ban['headImg']; if(preg_match('/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/', $ban['player'])) if($this->isAdmin()) echo $ban['player'] if(!$this->isAdmin())echo 'IP Redacted'; if(!preg_match('/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/', $ban['player'])) echo $ban['player']?> </td>

Test this, might work for now until someone can clean it up. I have not tested it because I don't run this plugin/panel myself.

**Comment by KiloJuliet** [comment]
Check the forks I made a working prototype. Had two gaming communities test it for me since I don't have a server. I suggest you pretty up the changes before merging them in.

**Comment by alphartdev** [comment]
Yeah these are some good ideas. I was planning to use `filter_var($player, FILTER_VALIDATE_IP)`and add a function directly in the BaseController to avoid repeating code.

**Comment by KiloJuliet** [comment]
As I said I'm not really a php programmer here, it's a quick and dirty patch to get people secure for now, until it can be recoded.

**Comment by alphartdev** [comment]
Ok, thanks for the code anyway :D
