### ISSUE TITLE
Need Help with web-interface

### ISSUE THREAD

**Issue by Gregin** [alphartdev/BAT-WebInterface#6]
I can't get it to connect work, I have the mySQL connected but when creating an admin account, I click on the "create account" and nothing happens!!!!!!!!!

**Comment by alphartdev** [comment]
It's working fine on my side (version 1.6)
AFAIK last time someone met this issue, the webserver had a special feature and the directory change had some problems.
Open the firefox console and then click on the button, a message should appeared.


There is another option, I mentionned on BAT topic, here it is : 
So first, you must create a salt which is 16 characters-long. A salt is just a random string so take whatever string you want (you can use a password generator to generate it) and take the first 16 characters.
Once you got your salt, you're going to hash (with SHA-512) it with your password.
Let's take an example, if your password is "123456789" and your salt is "686f0e2655859187", just concatenate the two and it will give you a string like that : "123456789686f0e2655859187".
Enter this string on this website : http://www.miniwebtool.com/sha512-hash-generator/, click on the button to generate the hash and then copy the result, that's your hashed password.

Once you've done that, go in your database and insert an row with these data :
id: let it empty
user: yourUsername
password: your hashed password you just copied from the website above
salt: your salt
superuser: 1

In order to achieve that, if you're using MySQL console, look at the internet there are tons of tutorials about SQL language. Otherwise if you use PHPMyAdmin, just go in the database and browse to the bat_web table. There should be a button called "Insert", just click on it and insert the data as described above.
Finally, I have to warn you : __if the installation process has not worked, there is an issue with your browser or your webserver (or maybe BAT code) and the webinterface may not work properly even if you manage to create an accout with the manual way.__

**Comment by Gregin** [comment]
Thanks for laying it out all clear and organised, I will definitely try this. When I load the webinterface, the page goes white(for a few seconds) and then goes back to my home page. 
ex.
webpage.com
webpage.com/bans (interface)

**Comment by alphartdev** [comment]
Doing some cleaning.
I think we solved that some months ago, if I'm wrong reopen it/message me

**Comment by TiTo-418** [comment]
@alphartdev This is the error http://prntscr.com/bn8rs4

**Comment by alphartdev** [comment]
Yeah this error happens on some setup (if you open fully the debug console, you'll see it doesn't return json as expected but a whole html page).
Basically it depends on the location of the folder of the webinterface (I use files related operations during the setting during the installation process) on the server and the configuration of the webserver (usually Apache). 
I don't have enough skills in PHP to be able to handle the two types of setup so I used the most frequent one.
